#!/bin/bash
# This script is intended to be used with Ubuntu 22.04LTS and installs cockpit and the 45 drives modules for managing Samba and NFS shares

# Update Apt Repositories
sudo apt update -y

# Install Cockpit
sudo apt install cockpit

# Setup Cockpit-File-Sharing APT Repository
curl -sSL https://repo.45drives.com/setup | sudo bash
sudo apt update
sudo apt install cockpit-file-sharing
