#!/bin/bash

# Set hostname variable
hostname=$(hostname)

clear

# Ask for SMTP relay credentials
read -p "Enter the username for the SMTP relay email address: " username
read -sp "Enter the password for the SMTP relay email address: " password
echo

# Define relayhost
relayhost="[smtp.nexusedgeit.com]:587"

# Install Postfix
sudo apt update && sudo apt install mailutils postfix -yy

clear

# Configure /etc/postfix/main.cf
cat <<EOF | sudo tee /etc/postfix/main.cf
# See /usr/share/postfix/main.cf.dist for a commented, more complete version

# Debian specific:  Specifying a file name will cause the first
# line of that file to be used as the name.  The Debian default
# is /etc/mailname.
#myorigin = /etc/mailname

smtpd_banner = \$myhostname ESMTP \$mail_name (Ubuntu)
biff = no

# appending .domain is the MUA's job.
append_dot_mydomain = no

# Uncomment the next line to generate "delayed mail" warnings
#delay_warning_time = 4h

readme_directory = no

# See http://www.postfix.org/COMPATIBILITY_README.html -- default to 3.6 on
# fresh installs.
compatibility_level = 3.6

# TLS parameters
smtpd_tls_cert_file=/etc/ssl/certs/ssl-cert-snakeoil.pem
smtpd_tls_key_file=/etc/ssl/private/ssl-cert-snakeoil.key
smtpd_tls_security_level=may

smtp_tls_CApath=/etc/ssl/certs
#smtp_tls_security_level=may
smtp_tls_session_cache_database = btree:\${data_directory}/smtp_scache

smtpd_relay_restrictions = permit_mynetworks permit_sasl_authenticated defer_unauth_destination
myhostname = ${hostname}.nexusedgeit.com
alias_maps = hash:/etc/aliases
alias_database = hash:/etc/aliases
myorigin = /etc/mailname
mydestination = localhost.nexusedgeit.com, localhost
relayhost = ${relayhost}
mynetworks = 127.0.0.0/8 [::ffff:127.0.0.0]/104 [::1]/128
mailbox_size_limit = 0
recipient_delimiter = +
inet_interfaces = all
inet_protocols = ipv4

# Enable SASL authentication
smtp_sasl_auth_enable = yes
smtp_sasl_security_options = noanonymous
smtp_sasl_password_maps = hash:/etc/postfix/sasl_passwd
smtp_tls_security_level = encrypt
smtp_tls_CAfile = /etc/ssl/certs/ca-certificates.crt

sender_canonical_maps = hash:/etc/postfix/sender_canonical
EOF
sudo systemctl restart postfix

clear

# Configure /etc/postfix/sasl_passwd
sudo bash -c "echo '${relayhost} ${username}:${password}' > /etc/postfix/sasl_passwd"

# Secure the sasl_passwd file
sudo postmap /etc/postfix/sasl_passwd
sudo chown root:root /etc/postfix/sasl_passwd /etc/postfix/sasl_passwd.db
sudo chmod 0600 /etc/postfix/sasl_passwd /etc/postfix/sasl_passwd.db

# Configure /etc/postfix/sender_canonical
sudo bash -c "echo 'root@${hostname} ${username}' > /etc/postfix/sender_canonical"

# Apply sender_canonical mapping
sudo postmap /etc/postfix/sender_canonical
sudo systemctl restart postfix

# Configure /etc/aliases
sudo bash -c "echo 'root:          cjackson@nexusedgeit.com' >> /etc/aliases"
sudo newaliases

# Restart Postfix to apply changes
sudo systemctl restart postfix

echo "Postfix installation and configuration complete."

echo "Test email from Postfix" | mail -s "Test" cjackson@nexusedgeit.com
sudo tail -f /var/log/mail.log
